//========================================================================================
//  
//  $File: //depot/devtech/nevis/plugin/source/sdksamples/textexportfilter/TxtExpFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/03/06 12:15:34 $
//  
//  $Revision: #10 $
//  
//  $Change: 1009641 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//  
//  Each C++ implementation class in the plug-in and its corresponding ImplementationID
//  should be registered in this file.
//  
//========================================================================================

REGISTER_PMINTERFACE(TxtExpActionComponent, kTxtExpActionComponentImpl)
REGISTER_PMINTERFACE(TxtExpFilter, kTxtExpFilterImpl)
REGISTER_PMINTERFACE(TxtExpDialogController, kTxtExpDialogControllerImpl)
REGISTER_PMINTERFACE(TxtExpDialogObserver, kTxtExpDialogObserverImpl)
REGISTER_PMINTERFACE(ASCIIFileWriter, kASCIIFileWriterImpl)
REGISTER_PMINTERFACE(UNICODEFileWriter, kUNICODEFileWriterImpl)
REGISTER_PMINTERFACE(ShiftJISFileWriter, kShiftJISFileWriterImpl)
REGISTER_PMINTERFACE(JISFileWriter, kJISFileWriterImpl)
REGISTER_PMINTERFACE(TxtExpSuiteASB, kTxtExpSuiteASBImpl)
REGISTER_PMINTERFACE(TxtExpSuiteTextCSB, kTxtExpSuiteTextCSBImpl)

//  Generated by Dolly build 17: template "IfPanelMenu".
// End, TxtExpFactoryList.h.



