//========================================================================================
//  
//  $File: //depot/devtech/nevis/plugin/source/sdksamples/printmemorystream/PrtMemFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/03/06 12:15:34 $
//  
//  $Revision: #10 $
//  
//  $Change: 1009641 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(PrtMemActionComponent, kPrtMemActionComponentImpl)
REGISTER_PMINTERFACE(PrtMemPrintSetupProvider, kPrtMemPrintSetupProviderImpl)
REGISTER_PMINTERFACE(PrtMemPrintDataHelperStrategy, kPrtMemPrintDataHelperStrategyImpl)
REGISTER_PMINTERFACE(PrtMemHelperStrategyService, kPrtMemHelperStrategyServiceImpl)
REGISTER_PMINTERFACE(PrtMemWriteStream, kPrtMemWriteStreamImpl)
REGISTER_PMINTERFACE(PrtMemPrintInsertPSProcProvider, kPrtMemPrintInsertPSProcProviderImpl)
//  Code generated by DollyXS code generator
