//========================================================================================
//  
//  $File: //depot/devtech/nevis/plugin/source/sdksamples/xmlcataloghandler/XCatHndFactoryList.h $
//  
//  Owner: Adobe Developer Technologies
//  
//  $Author: pmbuilder $
//  
//  $DateTime: 2018/03/06 12:15:34 $
//  
//  $Revision: #10 $
//  
//  $Change: 1009641 $
//  
//  Copyright 1997-2010 Adobe Systems Incorporated. All rights reserved.
//  
//  NOTICE:  Adobe permits you to use, modify, and distribute this file in accordance 
//  with the terms of the Adobe license agreement accompanying it.  If you have received
//  this file from a source other than Adobe, then your use, modification, or 
//  distribution of it requires the prior written permission of Adobe.
//  
//========================================================================================

REGISTER_PMINTERFACE(XCatHndParsingContext, kXCatHndParsingContextImpl)
REGISTER_PMINTERFACE(XCatHndSAXContentHandler, kXCatHndSAXContentHandlerImpl)
REGISTER_PMINTERFACE(XCatHndEntityMapping, kXCatHndEntityMappingImpl)
REGISTER_PMINTERFACE(XCatHndEntityResolver, kXCatHndEntityResolverImpl)
REGISTER_PMINTERFACE(XCatHndChangeEntityMappingCmd, kXCatHndChangeEntityMappingCmdImpl)
REGISTER_PMINTERFACE(XCatHndFacade, kXCatHndFacadeImpl)
REGISTER_PMINTERFACE(XCatHndAcquirerFilter, kXCatHndAcquirerFilterImpl)
REGISTER_PMINTERFACE(XCatHndStartupShutdown, kXCatHndStartupShutdownImpl)
REGISTER_PMINTERFACE(XCatHndErrorStringService, kXCatHndErrorStringServiceImpl)
REGISTER_PMINTERFACE(XCatHndAcquirerXMLImportPrefs, kXCatHndAcquirerXMLImportPrefsImpl)
//  Code generated by DollyXS code generator
